package majsoul

import (
	"context"

	"github.com/constellation39/majsoul/message"
)

// IFNotify
// 雀魂proto协议中缺少描述监听消息的接口
// 故添加该接口，可能会丢失某些api
// 有没有更聪明点的办法？
type IFNotify interface {
	NotifyCaptcha(ctx context.Context, notify *message.NotifyCaptcha)
	NotifyRoomGameStart(ctx context.Context, notify *message.NotifyRoomGameStart)
	NotifyMatchGameStart(ctx context.Context, notify *message.NotifyMatchGameStart)
	NotifyRoomPlayerReady(ctx context.Context, notify *message.NotifyRoomPlayerReady)
	NotifyRoomPlayerDressing(ctx context.Context, notify *message.NotifyRoomPlayerDressing)
	NotifyRoomPlayerUpdate(ctx context.Context, notify *message.NotifyRoomPlayerUpdate)
	NotifyRoomKickOut(ctx context.Context, notify *message.NotifyRoomKickOut)
	NotifyFriendStateChange(ctx context.Context, notify *message.NotifyFriendStateChange)
	NotifyFriendViewChange(ctx context.Context, notify *message.NotifyFriendViewChange)
	NotifyFriendChange(ctx context.Context, notify *message.NotifyFriendChange)
	NotifyNewFriendApply(ctx context.Context, notify *message.NotifyNewFriendApply)
	NotifyClientMessage(ctx context.Context, notify *message.NotifyClientMessage)
	NotifyAccountUpdate(ctx context.Context, notify *message.NotifyAccountUpdate)
	NotifyAnotherLogin(ctx context.Context, notify *message.NotifyAnotherLogin)
	NotifyAccountLogout(ctx context.Context, notify *message.NotifyAccountLogout)
	NotifyAnnouncementUpdate(ctx context.Context, notify *message.NotifyAnnouncementUpdate)
	NotifyNewMail(ctx context.Context, notify *message.NotifyNewMail)
	NotifyDeleteMail(ctx context.Context, notify *message.NotifyDeleteMail)
	NotifyReviveCoinUpdate(ctx context.Context, notify *message.NotifyReviveCoinUpdate)
	NotifyDailyTaskUpdate(ctx context.Context, notify *message.NotifyDailyTaskUpdate)
	NotifyActivityTaskUpdate(ctx context.Context, notify *message.NotifyActivityTaskUpdate)
	NotifyActivityPeriodTaskUpdate(ctx context.Context, notify *message.NotifyActivityPeriodTaskUpdate)
	NotifyAccountRandomTaskUpdate(ctx context.Context, notify *message.NotifyAccountRandomTaskUpdate)
	NotifyActivitySegmentTaskUpdate(ctx context.Context, notify *message.NotifyActivitySegmentTaskUpdate)
	NotifyActivityUpdate(ctx context.Context, notify *message.NotifyActivityUpdate)
	NotifyAccountChallengeTaskUpdate(ctx context.Context, notify *message.NotifyAccountChallengeTaskUpdate)
	NotifyNewComment(ctx context.Context, notify *message.NotifyNewComment)
	NotifyRollingNotice(ctx context.Context, notify *message.NotifyRollingNotice)
	NotifyGiftSendRefresh(ctx context.Context, notify *message.NotifyGiftSendRefresh)
	NotifyShopUpdate(ctx context.Context, notify *message.NotifyShopUpdate)
	NotifyVipLevelChange(ctx context.Context, notify *message.NotifyVipLevelChange)
	NotifyServerSetting(ctx context.Context, notify *message.NotifyServerSetting)
	NotifyPayResult(ctx context.Context, notify *message.NotifyPayResult)
	NotifyCustomContestAccountMsg(ctx context.Context, notify *message.NotifyCustomContestAccountMsg)
	NotifyCustomContestSystemMsg(ctx context.Context, notify *message.NotifyCustomContestSystemMsg)
	NotifyMatchTimeout(ctx context.Context, notify *message.NotifyMatchTimeout)
	NotifyCustomContestState(ctx context.Context, notify *message.NotifyCustomContestState)
	NotifyActivityChange(ctx context.Context, notify *message.NotifyActivityChange)
	NotifyAFKResult(ctx context.Context, notify *message.NotifyAFKResult)
	NotifyGameFinishRewardV2(ctx context.Context, notify *message.NotifyGameFinishRewardV2)
	NotifyActivityRewardV2(ctx context.Context, notify *message.NotifyActivityRewardV2)
	NotifyActivityPointV2(ctx context.Context, notify *message.NotifyActivityPointV2)
	NotifyLeaderboardPointV2(ctx context.Context, notify *message.NotifyLeaderboardPointV2)
	NotifyNewGame(ctx context.Context, notify *message.NotifyNewGame)
	NotifyPlayerLoadGameReady(ctx context.Context, notify *message.NotifyPlayerLoadGameReady)
	NotifyGameBroadcast(ctx context.Context, notify *message.NotifyGameBroadcast)
	NotifyGameEndResult(ctx context.Context, notify *message.NotifyGameEndResult)
	NotifyGameTerminate(ctx context.Context, notify *message.NotifyGameTerminate)
	NotifyPlayerConnectionState(ctx context.Context, notify *message.NotifyPlayerConnectionState)
	NotifyAccountLevelChange(ctx context.Context, notify *message.NotifyAccountLevelChange)
	NotifyGameFinishReward(ctx context.Context, notify *message.NotifyGameFinishReward)
	NotifyActivityReward(ctx context.Context, notify *message.NotifyActivityReward)
	NotifyActivityPoint(ctx context.Context, notify *message.NotifyActivityPoint)
	NotifyLeaderboardPoint(ctx context.Context, notify *message.NotifyLeaderboardPoint)
	NotifyGamePause(ctx context.Context, notify *message.NotifyGamePause)
	NotifyEndGameVote(ctx context.Context, notify *message.NotifyEndGameVote)
	NotifyObserveData(ctx context.Context, notify *message.NotifyObserveData)
	NotifyRoomPlayerReady_AccountReadyState(ctx context.Context, notify *message.NotifyRoomPlayerReady_AccountReadyState)
	NotifyRoomPlayerDressing_AccountDressingState(ctx context.Context, notify *message.NotifyRoomPlayerDressing_AccountDressingState)
	NotifyAnnouncementUpdate_AnnouncementUpdate(ctx context.Context, notify *message.NotifyAnnouncementUpdate_AnnouncementUpdate)
	NotifyActivityUpdate_FeedActivityData(ctx context.Context, notify *message.NotifyActivityUpdate_FeedActivityData)
	NotifyActivityUpdate_FeedActivityData_CountWithTimeData(ctx context.Context, notify *message.NotifyActivityUpdate_FeedActivityData_CountWithTimeData)
	NotifyActivityUpdate_FeedActivityData_GiftBoxData(ctx context.Context, notify *message.NotifyActivityUpdate_FeedActivityData_GiftBoxData)
	NotifyPayResult_ResourceModify(ctx context.Context, notify *message.NotifyPayResult_ResourceModify)
	NotifyGameFinishRewardV2_LevelChange(ctx context.Context, notify *message.NotifyGameFinishRewardV2_LevelChange)
	NotifyGameFinishRewardV2_MatchChest(ctx context.Context, notify *message.NotifyGameFinishRewardV2_MatchChest)
	NotifyGameFinishRewardV2_MainCharacter(ctx context.Context, notify *message.NotifyGameFinishRewardV2_MainCharacter)
	NotifyGameFinishRewardV2_CharacterGift(ctx context.Context, notify *message.NotifyGameFinishRewardV2_CharacterGift)
	NotifyActivityRewardV2_ActivityReward(ctx context.Context, notify *message.NotifyActivityRewardV2_ActivityReward)
	NotifyActivityPointV2_ActivityPoint(ctx context.Context, notify *message.NotifyActivityPointV2_ActivityPoint)
	NotifyLeaderboardPointV2_LeaderboardPoint(ctx context.Context, notify *message.NotifyLeaderboardPointV2_LeaderboardPoint)
	NotifyGameFinishReward_LevelChange(ctx context.Context, notify *message.NotifyGameFinishReward_LevelChange)
	NotifyGameFinishReward_MatchChest(ctx context.Context, notify *message.NotifyGameFinishReward_MatchChest)
	NotifyGameFinishReward_MainCharacter(ctx context.Context, notify *message.NotifyGameFinishReward_MainCharacter)
	NotifyGameFinishReward_CharacterGift(ctx context.Context, notify *message.NotifyGameFinishReward_CharacterGift)
	NotifyActivityReward_ActivityReward(ctx context.Context, notify *message.NotifyActivityReward_ActivityReward)
	NotifyActivityPoint_ActivityPoint(ctx context.Context, notify *message.NotifyActivityPoint_ActivityPoint)
	NotifyLeaderboardPoint_LeaderboardPoint(ctx context.Context, notify *message.NotifyLeaderboardPoint_LeaderboardPoint)
	NotifyEndGameVote_VoteResult(ctx context.Context, notify *message.NotifyEndGameVote_VoteResult)
	PlayerLeaving(ctx context.Context, notify *message.PlayerLeaving)
	ActionPrototype(ctx context.Context, notify *message.ActionPrototype)
}
